;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        cam/join-next-line
        clojure-toggle-keyword-string
        electric-newline-and-maybe-indent
        electric-pair-delete-pair
        forward-sexp
        indent-for-tab-command
        insert-register
        join-next-line
        kill-region
        kill-sexp
        kmacro-end-or-call-macro
        paredit-backslash
        paredit-backward
        paredit-close-curly
        paredit-close-round
        paredit-close-square
        paredit-doublequote
        paredit-forward
        paredit-forward-delete
        paredit-forward-slurp-sexp
        paredit-kill
        paredit-newline
        paredit-open-curly
        paredit-open-round
        paredit-open-square
        yaml-electric-backspace
        ))

(setq mc/cmds-to-run-once
      '(
        ace-jump-done
        ace-jump-mode
        beginning-of-buffer
        end-of-buffer
        helm-M-x
        jump-to-register
        mc/mark-next-lines
        next-buffer
        paredit-mode
        previous-buffer
        ))
