;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	paredit-backward
	paredit-forward
	paredit-forward-delete
	paredit-open-square
	))

(setq mc/cmds-to-run-once
      '(
	mc/mark-next-lines
	))
